# Generated by Django 4.2.2 on 2024-06-14 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите адрес электронной почты', max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, help_text='Введите имя (по желанию ФИО)', max_length=200, null=True, verbose_name='Имя')),
                ('comment', models.CharField(blank=True, help_text='Введите комментарий', max_length=300, null=True, verbose_name='Комментарий')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название рассылки', max_length=150, verbose_name='Название')),
                ('content', models.CharField(help_text='Введите содержание рассылки', max_length=300, verbose_name='Содержание')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало отправки рассылки')),
                ('end_time_last', models.DateTimeField(blank=True, null=True, verbose_name='Последняя дата отправки рассылки')),
                ('period', models.CharField(choices=[('ONCE_HOUR', 'Каждый час'), ('DAILY', 'Раз в день'), ('WEEKLY', 'Раз в неделю'), ('MONTHLY', 'Раз в месяц')], max_length=30, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('STARTED', 'Запущена'), ('COMPLETED', 'Завершена')], default='CREATED', max_length=30, verbose_name='Статус рассылки')),
                ('mail_active', models.BooleanField(default=True, verbose_name='Активность рассылки')),
                ('clients', models.ManyToManyField(related_name='client', to='mailings.client', verbose_name='Клиенты')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailings.message', verbose_name='Сообщение')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'permissions': [('change_status', 'Can change mailing status')],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка отправки')], default='CREATED', max_length=30, verbose_name='Cтатус попытки')),
                ('server_response', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ почтового сервера')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.mail', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
    ]
