# Generated by Django 4.2.2 on 2024-06-17 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='end_time_last',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Последняя дата отправки рассылки'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало отправки рассылки'),
        ),
    ]
